spring:
  application:
    name: backend

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

zai:
  api-key: ${ZAI_API_KEY}
  base-url: ${ZAI_BASE_URL}
  model: ${ZAI_MODEL}